# From: https://rohitgupta.xyz/blog/keeping-python-code-clean-with-pre-commit-hooks-black-flake8-and-isort/

repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
    - id: pycln
  - repo: https://github.com/ambv/black
    rev: 23.12.1
    hooks:
    - id: black
      language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.343
    hooks:
    - id: pyright
  - repo: https://github.com/pre-commit/pre-commit-hooks 
    rev: v4.5.0  # Use the sha / tag you want to point at
    hooks:
    - id: debug-statements
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.26
    hooks:
    - id: typos
      args: []
