name: async-whisper
channels:
  - conda-forge
  - nodefaults
dependencies:
  - black
  - ffmpeg
  - openai
  - pip
  - pre-commit
  - pydub
  - pyright
  - python>=3.9
  - pip:
    - aiolimiter
    - simpleaudio
    - thefuzz
